### PR TITLE
fix: allow dots and colons in project id

### LINKED ISSUE #33: CloudSpanner JDBC: Project IDs that contain period and colon fail URL matching when creating connections
#### Environment details

1. API: CloudSpanner JDBC
2. OS type and version: Windows 10
3. Java version: 8 
4. spanner-jdbc version(s): 1.12.0

#### Steps to reproduce

  1. have a google cloud platform project ID that has a period and a colon (we created this project before Google restricted project IDs to having only letters, numbers, and hyphens). I suppose this is a grandfathered project ID. 
  2. try to use the project ID in creating the connection string. ours look like this: 
`jdbc:cloudspanner:/projects/safe.com:fme-big-query-api/instances/myinstance/databases/mydb`

result:
error
```
com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: invalid url: jdbc:cloudspanner:/projects/safe.com:fme-big-query-api/instances/myinstance/databases/mydb
```

#### Code example

```java
      String driverClassName = JdbcDriver.class.getCanonicalName();
      Class<?> driverClass = Class.forName(driverClassName);
      Driver driver = (Driver)driverClass.newInstance();
      Connection connection = driver.connect(connString, connProps);
```

#### Stack trace
```
com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: invalid url: jdbc:cloudspanner:/projects/safe.com:fme-big-query-api/instances/myinstance/databases/mydb

	at com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory.of(JdbcSqlExceptionFactory.java:234)
	at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:174)
```

Thanks!

### PR DESCRIPTION
**Pull request by olavloite**
The project ID part of a connection URL should allow the use of dots and colons. This PR also replaces all usages of the deprecated class `org.junit.Assert` in the affected test classes with `com.google.common.truth.Truth`.

Fixes #33

### CODE REVIEW

File: src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java [hunk 1]
```diff
@@ -231,7 +231,7 @@ private Builder() {}
 
     /** Spanner {@link ConnectionOptions} URI format. */
     public static final String SPANNER_URI_FORMAT =
-        "(?:cloudspanner:)(?<HOSTGROUP>//[\\w.-]+(?:\\.[\\w\\.-]+)*[\\w\\-\\._~:/?#\\[\\]@!\\$&'\\(\\)\\*\\+,;=.]+)?/projects/(?<PROJECTGROUP>(([a-z]|[-]|[0-9])+|(DEFAULT_PROJECT_ID)))(/instances/(?<INSTANCEGROUP>([a-z]|[-]|[0-9])+)(/databases/(?<DATABASEGROUP>([a-z]|[-]|[_]|[0-9])+))?)?(?:[?|;].*)?";
+        "(?:cloudspanner:)(?<HOSTGROUP>//[\\w.-]+(?:\\.[\\w\\.-]+)*[\\w\\-\\._~:/?#\\[\\]@!\\$&'\\(\\)\\*\\+,;=.]+)?/projects/(?<PROJECTGROUP>(([a-z]|[-\\.:]|[0-9])+|(DEFAULT_PROJECT_ID)))(/instances/(?<INSTANCEGROUP>([a-z]|[-]|[0-9])+)(/databases/(?<DATABASEGROUP>([a-z]|[-]|[_]|[0-9])+))?)?(?:[?|;].*)?";
```
Comment (hengfengli) [inline src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java]: Is `\` allowed in the project id? Why do we allow `\` as well?

Comment (hengfengli) [reply src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java]: Forget about my above comment. I just realise that `\\` will be escape to `\` by java string, and then `\.` is regex string. 

nits: I don't think `.` needs to be escaped in the `[]`. `[-.:]` also works fine, but it doesn't hurt to escape it.

Comment (olavloite) [reply src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java]: I removed the escaping as it makes it more readable. Thanks for pointing it out.
