### PR TITLE
docs: fix javadoc formatting

### LINKED ISSUE #342: Documentation for connection properties are not formatted correctly.
#### External references such as API reference guides

When reviewing the [API documentation for JdbcDriver](https://googleapis.dev/java/google-cloud-spanner-jdbc/latest/index.html), I found that the content for `optimizerVersion` is not well-formatted. For the source, it seems that it missed a [closing code block element](https://github.com/googleapis/java-spanner-jdbc/blob/9b53df4ea33926d9fa0955a4445c2ea6790ac3dc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java#L92).

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by olavloite**
One of the descriptions of the supported connection properties missed an ending `</code>` block, which caused the entire formatting to be incorrect.

Fixes #342

### CODE REVIEW

File: src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java [hunk 1]
```diff
@@ -89,8 +89,15 @@
...
- *   <li>optimizerVersion (string): The query optimizer version to use for the connection. The value must be either a valid version number or <code>LATEST</code>. If no value is specified, the query optimizer version specified in the environment variable <code>SPANNER_OPTIMIZER_VERSION<code> will be used. If no query optimizer version is specified in the connection URL or in the environment variable, the default query optimizer version of Cloud Spanner will be used.
+ *   <li>usePlainText (boolean): Sets whether the JDBC connection should establish an unencrypted
+ *       connection to the server. This option can only be used when connecting to a local emulator
+ *       that does not require an encrypted connection, and that does not require authentication.
+ *   <li>optimizerVersion (string): The query optimizer version to use for the connection. The value
+ *       must be either a valid version number or <code>LATEST</code>. If no value is specified, the
+ *       query optimizer version specified in the environment variable <code>
+ *       SPANNER_OPTIMIZER_VERSION</code> will be used. If no query optimizer version is specified
```
Comment (elharo) [inline src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java:98]: will be --> is

**Review by elharo — APPROVED** [review]

File: src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java (hunk 1 above)
Comment (olavloite) [reply src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java]: Done.

**Review by thiagotnunes — APPROVED** [review]
